import { screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { buildApplication, buildResource, mockAPI } from '../../test/mock-api'
import { renderApp } from '../../test/render'

afterEach(() => {
  vi.restoreAllMocks()
})

describe('application manifests modal', () => {
  it('shows a controller-generated object as live YAML rather than a half-empty diff', async () => {
    mockAPI({
      applications: [buildApplication()],
      resources: [buildResource({ uid: 'uid-dep', kind: 'Deployment', name: 'payments-api' })],
      desiredManifest: '',
      manifest: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"name":"payments-api"}}',
    })
    renderApp('/applications/onboarding-1')
    const user = userEvent.setup()

    await user.click(await screen.findByRole('button', { name: 'Manifest' }))
    const modal = await screen.findByRole('dialog', { name: 'Kubernetes manifests' })
    const pane = await within(modal).findByLabelText('Manifest diff for payments-api')
    expect(pane).toHaveTextContent('Generated by a Kubernetes controller')
    expect(pane).not.toHaveTextContent('Helm rendered')
    expect(
      within(pane).getByLabelText('Live YAML for payments-api on prod-us-east'),
    ).toHaveTextContent('kind: Deployment')
    expect(within(pane).getByRole('button', { name: 'Wrap lines' })).toBeInTheDocument()
  })
})
