configs:
  cm:
    admin.enabled: false
    accounts.kubeops: apiKey, login
    accounts.kubeops.enabled: "true"
  rbac:
    policy.default: ""
    policy.csv: |
      p, role:kubeops, applications, create, */*, allow
      p, role:kubeops, applications, create, */*/*, allow
      p, role:kubeops, applications, get, */*, allow
      p, role:kubeops, applications, get, */*/*, allow
      p, role:kubeops, applications, sync, */*, allow
      p, role:kubeops, applications, sync, */*/*, allow
      p, role:kubeops, applications, delete, */*, allow
      p, role:kubeops, applications, delete, */*/*, allow
      p, role:kubeops, projects, get, *, allow
      g, kubeops, role:kubeops

dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  replicas: 0
