{{- if eq .Values.workload.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeops.workloadName" . }}
  labels:
    {{- include "kubeops.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.workload.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  strategy:
    {{- toYaml .Values.deploymentStrategy | nindent 4 }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kubeops.selectorLabels" . | nindent 6 }}
  template:
    {{- include "kubeops.podTemplate" . | nindent 4 }}
{{- end }}
