{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "kubeops.serviceName" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kubeops.resourceName" (dict "root" . "suffix" "ingress") }}
  labels:
    {{- include "kubeops.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (include "kubeops.ingressAnnotations" . | trim) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- with .Values.ingress.defaultBackend }}
  defaultBackend:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.hosts }}
  rules:
    {{- range . }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ default $serviceName .serviceName }}
                port:
                  {{- if .servicePort }}
                  {{- if kindIs "string" .servicePort }}
                  name: {{ .servicePort }}
                  {{- else }}
                  number: {{ .servicePort }}
                  {{- end }}
                  {{- else }}
                  number: {{ $servicePort }}
                  {{- end }}
          {{- end }}
          {{- with $.Values.ingress.extraPaths }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
