{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
# Requires the Prometheus Operator CRDs. AWS managed Prometheus, Google Managed
# Service for Prometheus and Azure Monitor managed Prometheus all consume
# ServiceMonitor and PodMonitor objects.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kubeops.resourceName" (dict "root" . "suffix" "servicemonitor") }}
  {{- with .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "kubeops.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "kubeops.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.metrics.portName }}
      path: {{ .Values.metrics.path }}
      scheme: {{ .Values.metrics.serviceMonitor.scheme }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- if and .Values.metrics.enabled .Values.metrics.podMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "kubeops.resourceName" (dict "root" . "suffix" "podmonitor") }}
  {{- with .Values.metrics.podMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "kubeops.labels" . | nindent 4 }}
    {{- with .Values.metrics.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.podMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "kubeops.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: {{ .Values.metrics.portName }}
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.podMonitor.interval }}
      {{- with .Values.metrics.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.metrics.podMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
