import { describe, expect, it } from 'vitest'
import { buildManifestDiff, prepareManifestPair } from './resource-diff'

describe('prepareManifestPair', () => {
  it('hides fields injected into the live object while keeping declared drift', () => {
    const desired = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2`
    const live = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  uid: generated
spec:
  replicas: 3
status:
  readyReplicas: 3`

    const focused = prepareManifestPair(desired, live, true)
    expect(focused.live).not.toContain('uid:')
    expect(focused.live).not.toContain('status:')
    expect(focused.live).toContain('replicas: 3')
  })

  it('identifies controller-generated resources without a desired object', () => {
    const prepared = prepareManifestPair(
      '',
      '{"apiVersion":"v1","kind":"Pod","metadata":{"name":"api-123"}}',
      true,
    )

    expect(prepared.desired).toContain('Generated by a Kubernetes controller')
    expect(prepared.live).toContain('kind: Pod')
  })
})

describe('buildManifestDiff', () => {
  it('aligns changed lines in a side-by-side diff', () => {
    const rows = buildManifestDiff('kind: Deployment\nreplicas: 2', 'kind: Deployment\nreplicas: 3')

    expect(rows).toEqual([
      {
        leftLine: 1,
        leftText: 'kind: Deployment',
        rightLine: 1,
        rightText: 'kind: Deployment',
        tone: 'same',
      },
      {
        leftLine: 2,
        leftText: 'replicas: 2',
        rightLine: 2,
        rightText: 'replicas: 3',
        tone: 'changed',
      },
    ])
  })
})
