import { parse, stringify } from 'yaml'

export type ManifestDiffRow = {
  leftLine?: number
  leftText?: string
  rightLine?: number
  rightText?: string
  tone: 'same' | 'changed' | 'removed' | 'added'
}

function pruneLiveToDesired(desired: unknown, live: unknown): unknown {
  if (Array.isArray(desired)) {
    if (!Array.isArray(live)) return live
    return live.map((item, index) =>
      index < desired.length ? pruneLiveToDesired(desired[index], item) : item,
    )
  }
  if (
    desired &&
    live &&
    typeof desired === 'object' &&
    typeof live === 'object' &&
    !Array.isArray(live)
  ) {
    const desiredRecord = desired as Record<string, unknown>
    const liveRecord = live as Record<string, unknown>
    return Object.fromEntries(
      Object.keys(desiredRecord).flatMap((key) =>
        key in liveRecord
          ? [[key, pruneLiveToDesired(desiredRecord[key], liveRecord[key])]]
          : [],
      ),
    )
  }
  return live
}

function format(value: unknown) {
  return stringify(value, { lineWidth: 0 }).trimEnd()
}

/**
 * Kubernetes controllers and admission webhooks add metadata, defaults, and
 * status after apply. In focused mode, retain only fields Helm declared while
 * preserving their live values so real drift remains visible.
 */
export function prepareManifestPair(
  desiredManifest: string,
  liveManifest: string,
  hideGeneratedFields: boolean,
) {
  try {
    const live = parse(liveManifest)
    if (!desiredManifest.trim()) {
      return {
        desired: '# Generated by a Kubernetes controller\n# No Helm-rendered object',
        live: format(live),
      }
    }
    const desired = parse(desiredManifest)
    return {
      desired: format(desired),
      live: format(hideGeneratedFields ? pruneLiveToDesired(desired, live) : live),
    }
  } catch {
    return {
      desired: desiredManifest.trimEnd(),
      live: liveManifest.trimEnd(),
    }
  }
}

type DiffOperation = {
  type: 'same' | 'removed' | 'added'
  text: string
}

function operations(left: string[], right: string[]): DiffOperation[] {
  const matrix = Array.from(
    { length: left.length + 1 },
    () => new Uint32Array(right.length + 1),
  )
  for (let leftIndex = left.length - 1; leftIndex >= 0; leftIndex--) {
    for (let rightIndex = right.length - 1; rightIndex >= 0; rightIndex--) {
      matrix[leftIndex][rightIndex] =
        left[leftIndex] === right[rightIndex]
          ? matrix[leftIndex + 1][rightIndex + 1] + 1
          : Math.max(
              matrix[leftIndex + 1][rightIndex],
              matrix[leftIndex][rightIndex + 1],
            )
    }
  }

  const result: DiffOperation[] = []
  let leftIndex = 0
  let rightIndex = 0
  while (leftIndex < left.length || rightIndex < right.length) {
    if (
      leftIndex < left.length &&
      rightIndex < right.length &&
      left[leftIndex] === right[rightIndex]
    ) {
      result.push({ type: 'same', text: left[leftIndex] })
      leftIndex++
      rightIndex++
    } else if (
      rightIndex >= right.length ||
      (leftIndex < left.length &&
        matrix[leftIndex + 1][rightIndex] >= matrix[leftIndex][rightIndex + 1])
    ) {
      result.push({ type: 'removed', text: left[leftIndex] })
      leftIndex++
    } else {
      result.push({ type: 'added', text: right[rightIndex] })
      rightIndex++
    }
  }
  return result
}

export function buildManifestDiff(desired: string, live: string): ManifestDiffRow[] {
  const result: ManifestDiffRow[] = []
  const pendingRemoved: string[] = []
  const pendingAdded: string[] = []
  let leftLine = 1
  let rightLine = 1

  const flush = () => {
    const count = Math.max(pendingRemoved.length, pendingAdded.length)
    for (let index = 0; index < count; index++) {
      const leftText = pendingRemoved[index]
      const rightText = pendingAdded[index]
      result.push({
        leftLine: leftText === undefined ? undefined : leftLine++,
        leftText,
        rightLine: rightText === undefined ? undefined : rightLine++,
        rightText,
        tone:
          leftText !== undefined && rightText !== undefined
            ? 'changed'
            : leftText !== undefined
              ? 'removed'
              : 'added',
      })
    }
    pendingRemoved.length = 0
    pendingAdded.length = 0
  }

  for (const operation of operations(desired.split('\n'), live.split('\n'))) {
    if (operation.type === 'removed') {
      pendingRemoved.push(operation.text)
    } else if (operation.type === 'added') {
      pendingAdded.push(operation.text)
    } else {
      flush()
      result.push({
        leftLine: leftLine++,
        leftText: operation.text,
        rightLine: rightLine++,
        rightText: operation.text,
        tone: 'same',
      })
    }
  }
  flush()
  return result
}
